spring.application.name=pilgrimgo
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://8.130.160.51:5432/BJTU2026
spring.datasource.username=BJTU2026
spring.datasource.password=BJTU2026Xunli+
spring.datasource.driver-class-name=org.postgresql.Driver

# Druid
spring.datasource.druid.initial-size=5
spring.datasource.druid.max-active=20
spring.datasource.druid.min-idle=5

# MyBatis-Plus
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true

# JWT
jwt.secret=PilgrimGoSecretKey2026BJTU2026XunliPlusApplicationJWT
jwt.expiration=86400000
