-- H2 测试数据库初始化脚本 (PostgreSQL 兼容模式)
-- 覆盖所有实体表，用于跨模块集成测试

-- 用户表
CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(20),
    email VARCHAR(100),
    password_hash VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500),
    nickname VARCHAR(50),
    bio VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 动漫作品表 (PK=bangumi_id, 与实体 Anime 保持一致)
CREATE TABLE IF NOT EXISTS anime (
    bangumi_id INT PRIMARY KEY,
    title_cn VARCHAR(200),
    title_jp VARCHAR(200),
    title_en VARCHAR(200),
    cat VARCHAR(50),
    cover_url VARCHAR(500),
    icon_url VARCHAR(500),
    description TEXT,
    city VARCHAR(100),
    color VARCHAR(20),
    abbr VARCHAR(50),
    site VARCHAR(200),
    release_date VARCHAR(20),
    default_lat DECIMAL(10, 8),
    default_lng DECIMAL(11, 8),
    default_zoom DECIMAL(5, 2),
    points_count INT DEFAULT 0,
    anitabi_modified BIGINT,
    synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 取景地表
CREATE TABLE IF NOT EXISTS spot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_id INT NOT NULL,
    anitabi_point_id VARCHAR(50),
    name_cn VARCHAR(200),
    name VARCHAR(200),
    image_url VARCHAR(500),
    episode INT,
    scene_seconds INT,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    origin VARCHAR(100),
    origin_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 路径表
CREATE TABLE IF NOT EXISTS route (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    anime_id INT,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    difficulty VARCHAR(20),
    estimated_minutes INT,
    distance_km DECIMAL(10, 2),
    gpx_file_url VARCHAR(500),
    avg_rating DECIMAL(3, 2) DEFAULT 0,
    rating_count INT DEFAULT 0,
    follow_count INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'approved',
    is_public BOOLEAN DEFAULT TRUE NOT NULL,
    recorded_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 路径轨迹点
CREATE TABLE IF NOT EXISTS route_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    sequence INT,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    altitude DECIMAL(8, 2),
    recorded_at TIMESTAMP
);

-- 路径转折点
CREATE TABLE IF NOT EXISTS waypoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    spot_id BIGINT,
    sequence INT,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    photo_url VARCHAR(500),
    instruction VARCHAR(500),
    waypoint_type VARCHAR(20)
);

-- 路径-取景地关联
CREATE TABLE IF NOT EXISTS route_spot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    spot_id BIGINT NOT NULL,
    visit_order INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 打卡记录
CREATE TABLE IF NOT EXISTS check_in (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    spot_id BIGINT NOT NULL,
    route_id BIGINT,
    photo_url VARCHAR(500),
    comparison_url VARCHAR(500),
    content TEXT,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    like_count INT DEFAULT 0,
    is_public BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 打卡点赞记录
CREATE TABLE IF NOT EXISTS checkin_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 巡礼记录（线上库遗留表，删除路径时需清理 route_id 引用）
CREATE TABLE IF NOT EXISTS pilgrimage_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    anime_id INT,
    route_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
